planesim:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  


  propeller_joint_controller:
    type: effort_controllers/JointVelocityController
    joint: propeller_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  left_wing_joint_controller:
    type: effort_controllers/JointPositionController
    joint: left_wing_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  right_wing_joint_controller:
    type: effort_controllers/JointPositionController
    joint: right_wing_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}