planesim:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  

  # Effort Controllers ---------------------------------------
  # left_aileron_effort_controller:
  #   type: effort_controllers/JointEffortController
  #   joint: left_aileron_joint
  #   pid: {p: 100.0, i: 0.1, d: 10.0}
  # right_aileron_effort_controller:
  #   type: effort_controllers/JointEffortController
  #   joint: right_aileron_joint
  #   pid: {p: 100.0, i: 0.1, d: 10.0}


  propeller_effort_controller:
      type: effort_controllers/JointEffortController
      joint: propeller_joint
      pid: {p: 100.0, i: 0.1, d: 10.0}